### ISSUE TITLE
Justyna RSS Feeds

### ISSUE THREAD

**Issue by Gabbendorf** [Gabbendorf/spindle#17]
We forked Justyna's repo and tried to add the RSS feeds in a new branch but realised that this is more complicated than expected. We thought that Justyna was saving her blog posts in a database but she's actually creating a new url for each post and a new view where she hard-codes the content.

Justyna said she would try to add the RSS feeds today (she didn't have time over the past weekend).
If she won't be able then she will just start using Medium.

**Comment by andrewMacmurray** [comment]
Closing this, as non trivial to add RSS to Justyna's blog, we've suggested that she uses Medium (or another blog format that implements RSS)
